# Generated by Django 6.0.2 on 2026-02-09 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_prescription_testrequest_worklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('water_intake', models.IntegerField(default=0, help_text='Number of glasses')),
                ('meditation_done', models.BooleanField(default=False)),
                ('healthy_food', models.BooleanField(default=False)),
                ('step_count', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
            options={
                'unique_together': {('patient', 'date')},
            },
        ),
    ]
