# Generated by Django 4.2.7 on 2026-02-09 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dailyhealthstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhealthstatus',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
