# Generated by Django 4.2.7 on 2026-02-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_is_pharmacy_pharmacyworker_staffhealthstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_dispensed',
            field=models.BooleanField(default=False),
        ),
    ]
