# Generated by Django 4.2.7 on 2026-02-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_prescription_is_dispensed'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffhealthstatus',
            name='is_on_duty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffhealthstatus',
            name='shift_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
