# Generated by Django 4.2.7 on 2026-02-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_emergencycase'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='last_taken',
            field=models.DateField(blank=True, null=True),
        ),
    ]
