# Generated by Django 5.2.6 on 2026-02-14 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_reminder_last_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='patient_upload',
            field=models.FileField(blank=True, null=True, upload_to='patient_uploads/'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='patient_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='result',
            field=models.TextField(blank=True, help_text="Lab technician's findings and analysis"),
        ),
        migrations.AddField(
            model_name='labreport',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='lab_results/'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='result_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to='core.labworker'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='test_type',
            field=models.CharField(choices=[('Blood Test', 'Blood Test'), ('Urine Test', 'Urine Test'), ('X-Ray', 'X-Ray'), ('MRI', 'MRI'), ('CT Scan', 'CT Scan'), ('ECG', 'ECG'), ('Ultrasound', 'Ultrasound'), ('Other', 'Other')], default='Blood Test', max_length=50),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(default='Nurse', max_length=50),
        ),
    ]
