# Generated by Django 5.2.6 on 2026-02-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_doctor_available_doctor_bio_doctor_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(default='Monday,Tuesday,Wednesday,Thursday,Friday', help_text='Days available (comma separated: Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday)', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_end_time',
            field=models.TimeField(blank=True, help_text='End of working hours', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_start_time',
            field=models.TimeField(blank=True, help_text='Start of working hours', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('General Medicine', 'General Medicine'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('Orthopedics', 'Orthopedics'), ('Dermatology', 'Dermatology'), ('Ophthalmology', 'Ophthalmology'), ('ENT', 'ENT'), ('Gynecology', 'Gynecology'), ('Psychiatry', 'Psychiatry'), ('Physiotherapy', 'Physiotherapy'), ('Dental', 'Dental'), ('Emergency', 'Emergency'), ('Other', 'Other')], default='General Medicine', help_text="Doctor's department", max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='max_appointments_per_day',
            field=models.IntegerField(default=10, help_text='Maximum appointments per day'),
        ),
    ]
