# Generated by Django 5.2.6 on 2026-02-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='duty_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='duty_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='duty_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
