# Generated by Django 5.2.6 on 2026-02-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_staff_duty_date_staff_duty_end_staff_duty_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='water_goal',
            field=models.IntegerField(default=8, help_text='Daily water intake goal in glasses'),
        ),
    ]
