# Generated by Django 4.2.7 on 2026-02-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_patient_water_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='labworker',
            name='image',
            field=models.ImageField(blank=True, help_text='Lab Worker photo', null=True, upload_to='lab_workers/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, help_text='Staff photo', null=True, upload_to='staff/'),
        ),
    ]
