# Generated by Django 4.2.7 on 2026-02-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_labworker_image_staff_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyworker',
            name='image',
            field=models.ImageField(blank=True, help_text='Pharmacy Worker photo', null=True, upload_to='pharmacy_workers/'),
        ),
    ]
