# Generated by Django 4.2.7 on 2026-02-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_pharmacyworker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='appointment_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Consultation fees', max_digits=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='salary_frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly')], default='Monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='labworker',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='labworker',
            name='salary_frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly')], default='Monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacyworker',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pharmacyworker',
            name='salary_frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly')], default='Monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='salary_frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly')], default='Monthly', max_length=20),
        ),
    ]
