# Generated by Django 4.2.7 on 2026-02-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='labworker',
            name='available_days',
            field=models.CharField(default='Monday,Tuesday,Wednesday,Thursday,Friday', help_text='Days available (comma separated)', max_length=100),
        ),
        migrations.AddField(
            model_name='labworker',
            name='available_end_time',
            field=models.TimeField(blank=True, help_text='End of working hours', null=True),
        ),
        migrations.AddField(
            model_name='labworker',
            name='available_start_time',
            field=models.TimeField(blank=True, help_text='Start of working hours', null=True),
        ),
        migrations.AddField(
            model_name='pharmacyworker',
            name='available_days',
            field=models.CharField(default='Monday,Tuesday,Wednesday,Thursday,Friday', help_text='Days available (comma separated)', max_length=100),
        ),
        migrations.AddField(
            model_name='pharmacyworker',
            name='available_end_time',
            field=models.TimeField(blank=True, help_text='End of working hours', null=True),
        ),
        migrations.AddField(
            model_name='pharmacyworker',
            name='available_start_time',
            field=models.TimeField(blank=True, help_text='Start of working hours', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='available_days',
            field=models.CharField(default='Monday,Tuesday,Wednesday,Thursday,Friday', help_text='Days available (comma separated)', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='available_end_time',
            field=models.TimeField(blank=True, help_text='End of working hours', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='available_start_time',
            field=models.TimeField(blank=True, help_text='Start of working hours', null=True),
        ),
    ]
