# Generated by Django 4.2.7 on 2026-02-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_labworker_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='extra_leave_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Salary deduction per extra leave day', max_digits=10),
        ),
        migrations.AddField(
            model_name='hospital',
            name='max_leave_days',
            field=models.IntegerField(default=12, help_text='Maximum allowed leave days per year'),
        ),
    ]
