# Generated by Django 4.2.7 on 2026-02-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_hospital_extra_leave_deduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
