# Generated by Django 4.2.7 on 2026-02-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='break_end_time',
            field=models.TimeField(blank=True, help_text='End of break/ward rounds', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='break_start_time',
            field=models.TimeField(blank=True, help_text='Start of break/ward rounds', null=True),
        ),
    ]
