# Generated by Django 4.2.7 on 2026-02-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_patient_age_patient_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffhealthstatus',
            name='is_present',
            field=models.BooleanField(default=False, help_text='Marked present for the day'),
        ),
    ]
