# Generated by Django 4.2.7 on 2026-02-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_staffhealthstatus_is_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Hospital Latitude', null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Hospital Longitude', null=True),
        ),
    ]
