# Generated by Django 4.2.7 on 2026-02-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_hospital_latitude_hospital_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='allowed_ip_address',
            field=models.CharField(blank=True, help_text='Comma-separated IP addresses allowed for marking attendance (e.g. 192.168.1.1, 203.0.113.5)', max_length=255, null=True),
        ),
    ]
