# Generated by Django 6.0.2 on 2026-02-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(help_text="Exact name of the test, e.g., 'Hemoglobin'", max_length=200)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], default='Any', help_text='Gender this range applies to', max_length=10)),
                ('min_age', models.IntegerField(default=0, help_text='Minimum age in years')),
                ('max_age', models.IntegerField(default=120, help_text='Maximum age in years')),
                ('condition', models.CharField(default='Any', help_text="Special conditions, e.g., 'Fasting'", max_length=100)),
                ('normal_range', models.CharField(help_text="The normal range to display, e.g., '13.8 - 17.2'", max_length=100)),
                ('unit', models.CharField(help_text="Unit of measurement, e.g., 'g/dL'", max_length=50)),
            ],
            options={
                'ordering': ['test_name', 'sex', 'min_age'],
                'unique_together': {('test_name', 'sex', 'min_age', 'max_age', 'condition')},
            },
        ),
    ]
