# Generated by Django 6.0.2 on 2026-03-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_labtestreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
