# Generated by Django 4.2.7 on 2026-03-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_ambulance_ambulancecall_medicine_patientadmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='meet_link',
            field=models.URLField(blank=True, help_text='Video consultation link (auto-generated or manually set by doctor)', max_length=500, null=True),
        ),
    ]
