# Generated by Django 4.2.7 on 2026-03-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_appointment_meet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='nurses',
            field=models.ManyToManyField(blank=True, help_text='Nurses assigned to this ward', limit_choices_to={'role': 'Nurse'}, related_name='assigned_wards', to='core.staff'),
        ),
    ]
