# Generated by Django 4.2.7 on 2026-03-27 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_ward_nurses_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientWaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('Morning', 'Morning (6AM - 2PM)'), ('Afternoon', 'Afternoon (2PM - 10PM)'), ('Night', 'Night (10PM - 6AM)')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('glasses', models.IntegerField(default=0, help_text='Number of glasses consumed')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_intakes', to='core.patientadmission')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_water_intakes', to='core.staff')),
            ],
            options={
                'unique_together': {('admission', 'shift', 'date')},
            },
        ),
        migrations.CreateModel(
            name='NurseTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('Medicine', 'Medicine Given'), ('Injection', 'Injection Given'), ('Infection', 'Infection Check'), ('Vitals', 'Vitals Recorded'), ('Water', 'Water Intake Recorded'), ('Diet', 'Diet Check')], max_length=20)),
                ('shift', models.CharField(choices=[('Morning', 'Morning (6AM - 2PM)'), ('Afternoon', 'Afternoon (2PM - 10PM)'), ('Night', 'Night (10PM - 6AM)')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='core.patientadmission')),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to='core.staff')),
            ],
            options={
                'unique_together': {('admission', 'task_type', 'shift', 'date')},
            },
        ),
    ]
