# Generated by Django 4.2.7 on 2026-03-27 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_nurse_task_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseWaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('Morning', 'Morning (6AM - 2PM)'), ('Afternoon', 'Afternoon (2PM - 10PM)'), ('Night', 'Night (10PM - 6AM)')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('glasses', models.IntegerField(default=0, help_text='Number of glasses consumed')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('nurse', models.ForeignKey(limit_choices_to={'role': 'Nurse'}, on_delete=django.db.models.deletion.CASCADE, related_name='water_intakes', to='core.staff')),
            ],
            options={
                'unique_together': {('nurse', 'shift', 'date')},
            },
        ),
    ]
