"""URL routing for the PHLM REST API (mounted at /api/)."""
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from . import views

router = DefaultRouter()
router.register(r'hospitals', views.HospitalViewSet, basename='hospital')
router.register(r'doctors', views.DoctorViewSet, basename='doctor')
router.register(r'patients', views.PatientViewSet, basename='patient')
router.register(r'staff', views.StaffViewSet, basename='staff')
router.register(r'lab-workers', views.LabWorkerViewSet, basename='labworker')
router.register(r'pharmacy-workers', views.PharmacyWorkerViewSet, basename='pharmacyworker')
router.register(r'leave-requests', views.LeaveRequestViewSet, basename='leaverequest')
router.register(r'appointments', views.AppointmentViewSet, basename='appointment')
router.register(r'lab-reports', views.LabReportViewSet, basename='labreport')
router.register(r'prescriptions', views.PrescriptionViewSet, basename='prescription')
router.register(r'prescribed-medicines', views.PrescribedMedicineViewSet, basename='prescribedmedicine')
router.register(r'test-requests', views.TestRequestViewSet, basename='testrequest')
router.register(r'reminders', views.ReminderViewSet, basename='reminder')
router.register(r'daily-health', views.DailyHealthStatusViewSet, basename='dailyhealth')
router.register(r'staff-health', views.StaffHealthStatusViewSet, basename='staffhealth')
router.register(r'wards', views.WardViewSet, basename='ward')
router.register(r'admissions', views.PatientAdmissionViewSet, basename='admission')
router.register(r'nurse-workloads', views.NurseWorkloadViewSet, basename='nurseworkload')
router.register(r'patient-water', views.PatientWaterIntakeViewSet, basename='patientwater')
router.register(r'nurse-task-logs', views.NurseTaskLogViewSet, basename='nursetasklog')
router.register(r'nurse-water', views.NurseWaterIntakeViewSet, basename='nursewater')
router.register(r'medicines', views.MedicineViewSet, basename='medicine')
router.register(r'injection-schedules', views.InjectionScheduleViewSet, basename='injectionschedule')
router.register(r'monitoring-logs', views.PatientMonitoringLogViewSet, basename='monitoringlog')
router.register(r'ambulances', views.AmbulanceViewSet, basename='ambulance')
router.register(r'ambulance-calls', views.AmbulanceCallViewSet, basename='ambulancecall')
router.register(r'emergencies', views.EmergencyCaseViewSet, basename='emergency')
router.register(r'notifications', views.NotificationViewSet, basename='notification')
router.register(r'lab-references', views.LabTestReferenceViewSet, basename='labreference')
router.register(r'alarms', views.PersistentAlarmViewSet, basename='alarm')
router.register(r'enhanced-emergencies', views.EnhancedEmergencyCaseViewSet, basename='enhancedemergency')
router.register(r'payments', views.PaymentViewSet, basename='payment')
router.register(r'auto-credentials', views.AutoGeneratedCredentialsViewSet, basename='autocredentials')
router.register(r'discharge-summaries', views.DischargeSummaryViewSet, basename='dischargesummary')
router.register(r'audit-logs', views.AuditLogViewSet, basename='auditlog')
router.register(r'insurance-providers', views.InsuranceProviderViewSet, basename='insuranceprovider')
router.register(r'insurance-policies', views.InsurancePolicyViewSet, basename='insurancepolicy')
router.register(r'insurance-claims', views.InsuranceClaimViewSet, basename='insuranceclaim')
router.register(r'family-members', views.FamilyMemberViewSet, basename='familymember')
router.register(r'health-wallet', views.HealthWalletItemViewSet, basename='healthwallet')
router.register(r'wearable-data', views.WearableDataViewSet, basename='wearabledata')
router.register(r'work-logs', views.WorkLogViewSet, basename='worklog')

urlpatterns = [
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('login/', views.LoginApiView.as_view(), name='api_login'),
    path('logout/', views.LogoutApiView.as_view(), name='api_logout'),
    path('profile/', views.ProfileApiView.as_view(), name='api_profile'),
    path('me/', views.MeApiView.as_view(), name='api_me'),
    path('', include(router.urls)),
]
