"""
DRF views & viewsets for the PHLM REST API.

Authentication uses DRF TokenAuthentication. The Flutter app logs in via
POST /api/login/ (no CSRF/session needed) and then sends the returned token
in the `Authorization: Token <token>` header for all other requests.

Every core model is exposed with full CRUD so the mobile app can read and write
the whole database. Hospital-scoped collections honour a `?hospital=<id>`
query parameter.
"""
from rest_framework import viewsets, status, permissions, views
from rest_framework.response import Response
from rest_framework.decorators import action
from rest_framework.authtoken.models import Token
from rest_framework.authentication import TokenAuthentication
from django.contrib.auth import authenticate

from core import models
from .serializers import (
    UserSerializer, HospitalSerializer, DoctorSerializer, PatientSerializer,
    StaffSerializer, LabWorkerSerializer, PharmacyWorkerSerializer,
    LeaveRequestSerializer, AppointmentSerializer, LabReportSerializer,
    PrescriptionSerializer, PrescribedMedicineSerializer, TestRequestSerializer,
    ReminderSerializer, DailyHealthStatusSerializer, StaffHealthStatusSerializer,
    WardSerializer, PatientAdmissionSerializer, NurseWorkloadSerializer,
    PatientWaterIntakeSerializer, NurseTaskLogSerializer,
    NurseWaterIntakeSerializer, MedicineSerializer, InjectionScheduleSerializer,
    PatientMonitoringLogSerializer, AmbulanceSerializer, AmbulanceCallSerializer,
    EmergencyCaseSerializer, NotificationSerializer, LabTestReferenceSerializer,
    PersistentAlarmSerializer, EnhancedEmergencyCaseSerializer,
    PaymentSerializer, AutoGeneratedCredentialsSerializer,
    DischargeSummarySerializer, AuditLogSerializer, InsuranceProviderSerializer,
    InsurancePolicySerializer, InsuranceClaimSerializer, FamilyMemberSerializer,
    HealthWalletItemSerializer, WearableDataSerializer, WorkLogSerializer,
)


class LoginApiView(views.APIView):
    """Exchange username/password for an auth token + profile."""

    permission_classes = [permissions.AllowAny]

    def post(self, request):
        username = (request.data.get('username') or '').strip()
        password = request.data.get('password') or ''
        user = authenticate(username=username, password=password)
        if user is None:
            return Response(
                {'detail': 'Invalid username or password.'},
                status=status.HTTP_400_BAD_REQUEST,
            )
        token, _ = Token.objects.get_or_create(user=user)
        return Response({'token': token.key, 'user': UserSerializer(user).data})


class LogoutApiView(views.APIView):
    """Delete the caller's auth token."""

    authentication_classes = [TokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def post(self, request):
        Token.objects.filter(user=request.user).delete()
        return Response({'detail': 'Logged out.'})


class ProfileApiView(views.APIView):
    """Return the currently authenticated user + role-specific profile."""

    authentication_classes = [TokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request):
        user = request.user
        data = UserSerializer(user).data
        profile = None
        if user.is_doctor and hasattr(user, 'doctor_profile'):
            profile = DoctorSerializer(user.doctor_profile).data
        elif user.is_patient and hasattr(user, 'patient_profile'):
            profile = PatientSerializer(user.patient_profile).data
        elif user.is_staff_member and hasattr(user, 'staff_profile'):
            profile = StaffSerializer(user.staff_profile).data
        elif user.is_lab and hasattr(user, 'lab_profile'):
            profile = LabWorkerSerializer(user.lab_profile).data
        elif user.is_pharmacy and hasattr(user, 'pharmacy_profile'):
            profile = PharmacyWorkerSerializer(user.pharmacy_profile).data
        elif user.is_hospital_admin and hasattr(user, 'hospital_profile'):
            profile = HospitalSerializer(user.hospital_profile).data
        data['profile'] = profile
        return Response(data)


class MeApiView(views.APIView):
    """Return the authenticated user's ID, username, role, and role-specific ID."""

    permission_classes = [permissions.IsAuthenticated]

    def get(self, request):
        user = request.user
        role = 'User'
        role_id = None

        if user.is_superuser:
            role = 'Superuser'
        elif user.is_hospital_admin:
            role = 'Hospital Admin'
            if hasattr(user, 'hospital_profile'):
                role_id = user.hospital_profile.id
        elif user.is_doctor:
            role = 'Doctor'
            if hasattr(user, 'doctor_profile'):
                role_id = user.doctor_profile.id
        elif user.is_patient:
            role = 'Patient'
            if hasattr(user, 'patient_profile'):
                role_id = user.patient_profile.id
        elif user.is_lab:
            role = 'Lab'
            if hasattr(user, 'lab_profile'):
                role_id = user.lab_profile.id
        elif user.is_pharmacy:
            role = 'Pharmacy'
            if hasattr(user, 'pharmacy_profile'):
                role_id = user.pharmacy_profile.id
        elif user.is_staff_member:
            if hasattr(user, 'staff_profile'):
                role = user.staff_profile.role  # 'Nurse' or 'Other'
                role_id = user.staff_profile.id
            else:
                role = 'Staff'

        return Response({
            'id': user.id,
            'username': user.username,
            'email': user.email,
            'role': role,
            'role_id': role_id
        })



class HospitalScopedViewSet(viewsets.ModelViewSet):
    """Base for collections that belong to a Hospital (filter by ?hospital=)."""

    hospital_filter_field = 'hospital'

    def get_queryset(self):
        qs = super().get_queryset()
        hospital_id = self.request.query_params.get('hospital')
        if hospital_id:
            qs = qs.filter(**{self.hospital_filter_field: hospital_id})
        return qs


# ---------------- Read/write ViewSets (one per model) ----------------

class HospitalViewSet(viewsets.ModelViewSet):
    queryset = models.Hospital.objects.all().order_by('id')
    serializer_class = HospitalSerializer
    authentication_classes = [TokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]


class DoctorViewSet(HospitalScopedViewSet):
    queryset = models.Doctor.objects.all().order_by('id')
    serializer_class = DoctorSerializer

    def get_queryset(self):
        qs = super().get_queryset()
        department = self.request.query_params.get('department')
        if department:
            qs = qs.filter(department=department)
        return qs


class PatientViewSet(HospitalScopedViewSet):
    queryset = models.Patient.objects.all().order_by('id')
    serializer_class = PatientSerializer


class StaffViewSet(HospitalScopedViewSet):
    queryset = models.Staff.objects.all().order_by('id')
    serializer_class = StaffSerializer


class LabWorkerViewSet(HospitalScopedViewSet):
    queryset = models.LabWorker.objects.all().order_by('id')
    serializer_class = LabWorkerSerializer


class PharmacyWorkerViewSet(HospitalScopedViewSet):
    queryset = models.PharmacyWorker.objects.all().order_by('id')
    serializer_class = PharmacyWorkerSerializer


class LeaveRequestViewSet(HospitalScopedViewSet):
    queryset = models.LeaveRequest.objects.all().order_by('id')
    serializer_class = LeaveRequestSerializer
    hospital_filter_field = 'doctor__hospital'


class AppointmentViewSet(HospitalScopedViewSet):
    queryset = models.Appointment.objects.all().order_by('id')
    serializer_class = AppointmentSerializer

    def get_queryset(self):
        qs = super().get_queryset()
        doctor_id = self.request.query_params.get('doctor')
        patient_id = self.request.query_params.get('patient')
        if doctor_id:
            qs = qs.filter(doctor_id=doctor_id)
        if patient_id:
            qs = qs.filter(patient_id=patient_id)
        return qs


class LabReportViewSet(HospitalScopedViewSet):
    queryset = models.LabReport.objects.all().order_by('id')
    serializer_class = LabReportSerializer


class PrescriptionViewSet(viewsets.ModelViewSet):
    queryset = models.Prescription.objects.all().order_by('id')
    serializer_class = PrescriptionSerializer


class PrescribedMedicineViewSet(viewsets.ModelViewSet):
    queryset = models.PrescribedMedicine.objects.all().order_by('id')
    serializer_class = PrescribedMedicineSerializer


class TestRequestViewSet(viewsets.ModelViewSet):
    queryset = models.TestRequest.objects.all().order_by('id')
    serializer_class = TestRequestSerializer


class ReminderViewSet(HospitalScopedViewSet):
    queryset = models.Reminder.objects.all().order_by('id')
    serializer_class = ReminderSerializer
    hospital_filter_field = 'patient__hospital'


class DailyHealthStatusViewSet(HospitalScopedViewSet):
    queryset = models.DailyHealthStatus.objects.all().order_by('id')
    serializer_class = DailyHealthStatusSerializer
    hospital_filter_field = 'patient__hospital'


class StaffHealthStatusViewSet(viewsets.ModelViewSet):
    queryset = models.StaffHealthStatus.objects.all().order_by('id')
    serializer_class = StaffHealthStatusSerializer


class WardViewSet(HospitalScopedViewSet):
    queryset = models.Ward.objects.all().order_by('id')
    serializer_class = WardSerializer


class PatientAdmissionViewSet(HospitalScopedViewSet):
    queryset = models.PatientAdmission.objects.all().order_by('id')
    serializer_class = PatientAdmissionSerializer


class NurseWorkloadViewSet(viewsets.ModelViewSet):
    queryset = models.NurseWorkload.objects.all().order_by('id')
    serializer_class = NurseWorkloadSerializer


class PatientWaterIntakeViewSet(viewsets.ModelViewSet):
    queryset = models.PatientWaterIntake.objects.all().order_by('id')
    serializer_class = PatientWaterIntakeSerializer


class NurseTaskLogViewSet(viewsets.ModelViewSet):
    queryset = models.NurseTaskLog.objects.all().order_by('id')
    serializer_class = NurseTaskLogSerializer


class NurseWaterIntakeViewSet(viewsets.ModelViewSet):
    queryset = models.NurseWaterIntake.objects.all().order_by('id')
    serializer_class = NurseWaterIntakeSerializer


class MedicineViewSet(HospitalScopedViewSet):
    queryset = models.Medicine.objects.all().order_by('id')
    serializer_class = MedicineSerializer


class InjectionScheduleViewSet(viewsets.ModelViewSet):
    queryset = models.InjectionSchedule.objects.all().order_by('id')
    serializer_class = InjectionScheduleSerializer


class PatientMonitoringLogViewSet(viewsets.ModelViewSet):
    queryset = models.PatientMonitoringLog.objects.all().order_by('id')
    serializer_class = PatientMonitoringLogSerializer


class AmbulanceViewSet(HospitalScopedViewSet):
    queryset = models.Ambulance.objects.all().order_by('id')
    serializer_class = AmbulanceSerializer


class AmbulanceCallViewSet(HospitalScopedViewSet):
    queryset = models.AmbulanceCall.objects.all().order_by('id')
    serializer_class = AmbulanceCallSerializer


class EmergencyCaseViewSet(HospitalScopedViewSet):
    queryset = models.EmergencyCase.objects.all().order_by('id')
    serializer_class = EmergencyCaseSerializer


class NotificationViewSet(viewsets.ModelViewSet):
    queryset = models.Notification.objects.all().order_by('id')
    serializer_class = NotificationSerializer

    def get_queryset(self):
        return models.Notification.objects.filter(
            recipient=self.request.user).order_by('id')

    @action(detail=True, methods=['post'])
    def read(self, request, pk=None):
        n = self.get_object()
        n.is_read = True
        n.save()
        return Response(NotificationSerializer(n).data)


class LabTestReferenceViewSet(viewsets.ModelViewSet):
    queryset = models.LabTestReference.objects.all().order_by('id')
    serializer_class = LabTestReferenceSerializer


class PersistentAlarmViewSet(HospitalScopedViewSet):
    queryset = models.PersistentAlarm.objects.all().order_by('id')
    serializer_class = PersistentAlarmSerializer


class EnhancedEmergencyCaseViewSet(viewsets.ModelViewSet):
    queryset = models.EnhancedEmergencyCase.objects.all().order_by('id')
    serializer_class = EnhancedEmergencyCaseSerializer


class PaymentViewSet(viewsets.ModelViewSet):
    queryset = models.Payment.objects.all().order_by('id')
    serializer_class = PaymentSerializer


class AutoGeneratedCredentialsViewSet(viewsets.ModelViewSet):
    queryset = models.AutoGeneratedCredentials.objects.all().order_by('id')
    serializer_class = AutoGeneratedCredentialsSerializer


class DischargeSummaryViewSet(viewsets.ModelViewSet):
    queryset = models.DischargeSummary.objects.all().order_by('id')
    serializer_class = DischargeSummarySerializer


class AuditLogViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = models.AuditLog.objects.all().order_by('id')
    serializer_class = AuditLogSerializer


class InsuranceProviderViewSet(HospitalScopedViewSet):
    queryset = models.InsuranceProvider.objects.all().order_by('id')
    serializer_class = InsuranceProviderSerializer


class InsurancePolicyViewSet(viewsets.ModelViewSet):
    queryset = models.InsurancePolicy.objects.all().order_by('id')
    serializer_class = InsurancePolicySerializer


class InsuranceClaimViewSet(viewsets.ModelViewSet):
    queryset = models.InsuranceClaim.objects.all().order_by('id')
    serializer_class = InsuranceClaimSerializer


class FamilyMemberViewSet(viewsets.ModelViewSet):
    queryset = models.FamilyMember.objects.all().order_by('id')
    serializer_class = FamilyMemberSerializer


class HealthWalletItemViewSet(viewsets.ModelViewSet):
    queryset = models.HealthWalletItem.objects.all().order_by('id')
    serializer_class = HealthWalletItemSerializer


class WearableDataViewSet(viewsets.ModelViewSet):
    queryset = models.WearableData.objects.all().order_by('id')
    serializer_class = WearableDataSerializer


class WorkLogViewSet(HospitalScopedViewSet):
    queryset = models.WorkLog.objects.all().order_by('id')
    serializer_class = WorkLogSerializer
    hospital_filter_field = 'doctor__hospital'
